#!/bin/bash
############################################################################################
## Publish the HoGS Theme to the Test Server

# To mount the router and webserver we need to have SSH access and SSH keys installed
# as we'll use sshfs to mount them if needed
rsa_file=/home/bernd/.ssh/id_rsa

# Web Server properties
server_name=Arachne
server_account=weaver@arachne.lan

server_mount_dir=$HOME/Mounts/hogs2020
server_dir=/data/www/HoGS/themes

# Get the source dir (we expect this script to be in the source dir)
source_dir=$(pwd)
echo "Source directory: $source_dir"

# Ensure the server is properly mounted (or we can't publish to them)
mountpoint -q $server_mount_dir
if [ $? != 0 ];then
	if [ ! -d $server_mount_dir ]; then
		echo "Creating destination directory $server_mount_dir ..."
	    mkdir -p $server_mount_dir
	fi

	echo Mounting $server_mount_dir ...
	sshfs -o IdentityFile=$rsa_file $server_account:$server_dir $server_mount_dir
else
	echo "Destination directory: $server_mount_dir"
fi

# Now publish the theme
echo "Copying theme to $server_name..."
rsync -r $source_dir/ $server_mount_dir/hogs2020

server_mount_dir=$HOME/Mounts/hogs2020_static
server_dir=/data/www/HoGS/static/themes


# Ensure the server is properly mounted (or we can't publish to them)
mountpoint -q $server_mount_dir
if [ $? != 0 ];then
	if [ ! -d $server_mount_dir ]; then
		echo "Creating destination directory $server_mount_dir ..."
	    mkdir -p $server_mount_dir
	fi

	echo Mounting $server_mount_dir ...
	sshfs -o IdentityFile=$rsa_file $server_account:$server_dir $server_mount_dir
else
	echo "Destination directory: $server_mount_dir"
fi

# Now publish the theme
echo "Copying media to $server_name..."
rsync -r $source_dir/media/ $server_mount_dir/hogs2020
